### ISSUE TITLE
error During Install

### ISSUE THREAD

**Issue by rajkiranjeet** [unknown-marketwizards/tradingview-desktop#3]
:\tradingview\tradingview-desktop\node_modules\@electron\get\dist\cjs\index.js:26
async function downloadArtifact(_artifactDetails) {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\tradingview\tradingview-desktop\node_modules\electron\install.js:9:30)
npm WARN tradingview-desktop@1.0.5 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@10.4.3 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@10.4.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\SNEHAL SIDHU\AppData\Roaming\npm-cache\_logs\2021-04-26T15_19_59_586Z-debug.log

C:\tradingview\tradingview-desktop>npm run build

> tradingview-desktop@1.0.5 build C:\tradingview\tradingview-desktop
> npx electron-builder build

'npx' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tradingview-desktop@1.0.5 build: `npx electron-builder build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tradingview-desktop@1.0.5 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\SNEHAL SIDHU\AppData\Roaming\npm-cache\_logs\2021-04-26T15_20_11_521Z-debug.log

C:\tradingview\tradingview-desktop>npm install

> core-js@3.11.0 postinstall C:\tradingview\tradingview-desktop\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

> electron@10.4.3 postinstall C:\tradingview\tradingview-desktop\node_modules\electron
> node install.js

C:\tradingview\tradingview-desktop\node_modules\@electron\get\dist\cjs\index.js:26
async function downloadArtifact(_artifactDetails) {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\tradingview\tradingview-desktop\node_modules\electron\install.js:9:30)
npm WARN tradingview-desktop@1.0.5 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@10.4.3 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@10.4.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\SNEHAL SIDHU\AppData\Roaming\npm-cache\_logs\2021-04-26T15_21_18_138Z-debug.log

C:\tradingview\tradingview-desktop>node install.js
module.js:471
    throw err;
    ^

Error: Cannot find module 'C:\tradingview\tradingview-desktop\install.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3

Please confirm whats wrong

**Comment by themarketwizard** [comment]
It looks like a network problem, 
try to run `npm install` again?
